added pet,requisite,species,animal type
McConderEz/AnimalAllies pull request #3
Opened 2024-08-08 19:46 UTC by McConderEz

2024-08-08 20:26 UTC, KirillSachkov requested changes

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/AnimalAllies.Domain.csproj
> +      <PackageReference Include="CSharpFunctionalExtensions" Version="2.42.5" />
Пока можно использовать эту либу, но в будущем советую сделать свой класс Result и тип Error

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Contraints/SpeciesConstraints.cs
> +    public static readonly int MAX_SPECIES_NAME_LENGTH = 100;
Чтобы каждый раз не создавать для всех сущностей константы с одинаковыми значениями, можно вынести общие константы в общий класс, и сделать там константы типа MIN_VALUE_LENGTH = 0, MIDDLE_VALUE_LENGTH=100, HIGH_VALUE_LENGTH и тд

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Models/AnimalType.cs
> +    public static Result<AnimalType> Create(int id, string name, List<Species> speciesList = null)
Для создания сущности id указывать не будем, ef core будем сам его генирировать

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Models/AnimalType.cs
> +    public static Result<AnimalType> Create(int id, string name, List<Species> speciesList = null)
лучше список приравнять не к null, а к пустому списку

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Models/AnimalType.cs
> +        var animalType = new AnimalType(id, name, speciesList == null ? speciesList : new List<Species>());
вместо new List<Species> можно написать []

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Models/Entity.cs
> +    public int Id { get; }
Мы будем использовать Guid

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Models/Entity.cs
> +    protected Entity(int id) => Id = id;
Нужно также написать предвидеть возможность не указывать id для создания сущности

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Models/Pet.cs
> +    public virtual Species? Species { get; }
Если мы следуем принципам DDD, то мы не можем иметь ссылку на сущность, которая находится в другом агрегате. Поэтому здесь не совсем верно построины связа между видом, породой и животным. Давай сейчас уберем временно вид и породу, сделаем их просто строками или value objects. Дальше я добавлю задание на создание этим сущностей

2024-08-08 20:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Domain/Models/Requisite.cs
> +public class Requisite
Это должен быть Value Object

2024-08-08 23:05 UTC, McConderEz commented on backend/src/AnimalAllies.Domain/Models/AnimalType.cs
> +    public static Result<AnimalType> Create(int id, string name, List<Species> speciesList = null)
Видимо ссылочные типы, отличные от string, нельзя приравнять ни к чему, кроме null

2024-08-09 05:19 UTC, KirillSachkov approved these changes

2024-08-09 18:31 UTC, merged