Id b 12
McConderEz/AnimalAllies pull request #32
Opened 2024-09-23 13:28 UTC by McConderEz

2024-09-24 07:26 UTC, KirillSachkov requested changes

2024-09-24 07:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.API/Controllers/SpeciesController.cs
> +    public async Task<IActionResult> CreateSpecies(
Species не нужно дописывать, потому что и мы в SpeciesController

2024-09-24 07:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.API/Controllers/SpeciesController.cs
> +
Если эти пустые строчки есть в коде, лучше их убирать

2024-09-24 07:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Application/Features/Species/Commands/DeleteBreed/DeleteBreedHandler.cs
> +        var result = species.Value.DeleteBreed(breedId);
Необходимо проверить, что если у хотя бы одного животного есть вид или порода, которую мы хотим удалить, то такой вид или породу удалять нельзя.

2024-09-24 07:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Application/Features/Species/Commands/DeleteSpecies/DeleteSpeciesHandler.cs
> +        var result = await _repository.Delete(species.Value, cancellationToken);
Необходимо проверить, что если у хотя бы одного животного есть вид или порода, которую мы хотим удалить, то такой вид или породу удалять нельзя.

2024-09-24 07:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Infrastructure.Postgres/Repositories/SpeciesRepository.cs
> +        await _context.SaveChangesAsync(cancellationToken);
Сохранение мы делаем с помощью unit of work, здесь оно не нужно

2024-09-24 07:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Infrastructure.Postgres/Repositories/SpeciesRepository.cs
> +        await _context.SaveChangesAsync(cancellationToken);
Сохранение мы делаем с помощью unit of work, здесь оно не нужно

2024-09-24 07:26 UTC, KirillSachkov commented on backend/src/AnimalAllies.Infrastructure.Postgres/Repositories/SpeciesRepository.cs
> +        await _context.SaveChangesAsync(cancellationToken);
Сохранение мы делаем с помощью unit of work, здесь оно не нужно

2024-09-24 20:28 UTC, McConderEz commented on backend/src/AnimalAllies.Application/Features/Species/Commands/DeleteBreed/DeleteBreedHandler.cs
> +    private readonly IVolunteerRepository _volunteerRepository;
Есть ли какой-то другой способ сделать проверки по животным, не создавая избыточную зависимость от другого агрегата через репозиторий волонтёра? Не придумал другой способ

2024-09-24 20:29 UTC, McConderEz commented on backend/src/AnimalAllies.Application/Features/Species/Commands/DeleteSpecies/DeleteSpeciesHandler.cs
> +    private readonly IVolunteerRepository _volunteerRepository;
Здесь тоже самое

2024-09-24 20:30 UTC, McConderEz commented on backend/src/AnimalAllies.Application/Features/Volunteer/Commands/AddPet/AddPetHandler.cs
> +        var isSpeciesExist = await _speciesRepository
Нам же нужно проверять, существуют ли тот или иной вид, а у него в свою очередь порода? Если да, то такая же проблема с зависимостью от репозитория видов

2024-09-25 13:15 UTC, KirillSachkov approved these changes

2024-09-25 13:15 UTC, KirillSachkov commented on backend/src/AnimalAllies.Application/Features/Species/Commands/DeleteBreed/DeleteBreedHandler.cs
> +    private readonly IVolunteerRepository _volunteerRepository;
Нет ничего плохого чтобы в одной фиче взаимодействовать в разными агрегатами. В будущем скорее всего одна фича будет взаимодействовать с разными системами и агрегатами, сложность будет рости. Главное соблюдать правило - один агрегат, одна транзакция. Если ты изменяешь один агрегат, то это должно происходить в его транзакции. Но если ты просто делаешь проверки, то это нормально

2024-09-25 13:15 UTC, KirillSachkov commented on backend/src/AnimalAllies.Application/Features/Volunteer/Commands/AddPet/AddPetHandler.cs
> +        var isSpeciesExist = await _speciesRepository
Да, нужно проверить, и опять же, такая зависимость, это не плохо, это норм. Можно сказать, что это даже обязательно

2024-09-25 13:27 UTC, merged