added accounts module,added jwt provider, added register and login handler, added user manager error extension,fix jwt, refactoring DependencyInjection.cs, added script migrations-add-and-update.cmd
McConderEz/AnimalAllies pull request #45
Opened 2024-10-11 14:29 UTC by McConderEz

2024-10-11 14:31 UTC, McConderEz commented
Jwt забыл в секреты кинуть

2024-10-12 10:36 UTC, KirillSachkov requested changes
Всё отлично, пару микрозамечаний

2024-10-12 10:36 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Infrastructure/JwtTokenProvider.cs
> +            new Claim(JwtRegisteredClaimNames.Name, user.UserName!)
Лучше сделать кастомный класс для типов клэймов, чтобы в будущем избежать ошибок

2024-10-12 10:36 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Presentation/Requests/LoginUserRequest.cs
> +public record LoginUserRequest(string Email, string Password)
Реквесты и респонсы должны лежать в папках с контрактами, поэтому там уже нельзя будет сделать методы ToCommand. Нужно исправить везде

2024-10-12 19:53 UTC, KirillSachkov approved these changes

2024-10-12 20:09 UTC, merged