Id b 21.1
McConderEz/AnimalAllies pull request #49
Opened 2024-10-23 17:37 UTC by McConderEz

2024-10-23 17:39 UTC, McConderEz commented on backend/src/BreedManagement/AnimalAllies.Species.Infrastructure/DependencyInjection.cs
> +            .AddServices(configuration);
Забыл, что в breed management нет soft удаления

2024-10-24 07:47 UTC, KirillSachkov requested changes

2024-10-24 07:47 UTC, KirillSachkov commented on backend/src/BreedManagement/AnimalAllies.Species.Domain/Entities/Breed.cs
> +public class Breed: SoftDeletableEntity<BreedId>
я бы не делал породу soft deletable, не вижу в этом смысла, пересоздать породу можно очень быстро

2024-10-24 07:47 UTC, KirillSachkov commented on backend/src/PetManagement/AnimalAllies.Volunteer.Infrastructure/BackgroundServices/EntityCleanerIfDeletedBackgroundService.cs
> +        await Task.CompletedTask;
тебе scope нужно открыть в цикле while, иначе у тебя будет открыт один scope вечно

2024-10-24 07:47 UTC, KirillSachkov commented on backend/src/PetManagement/AnimalAllies.Volunteer.Infrastructure/BackgroundServices/EntityCleanerIfDeletedBackgroundService.cs
> +        await Task.CompletedTask;
из-за этого могут быть проблемы с подключением к базе данных и акутальным состоянием

2024-10-24 10:09 UTC, KirillSachkov approved these changes

2024-10-24 10:10 UTC, merged