Id b 21.2
McConderEz/AnimalAllies pull request #50
Opened 2024-10-24 13:24 UTC by McConderEz

2024-10-24 14:58 UTC, KirillSachkov requested changes

2024-10-24 14:58 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var user = await GetUser(connection, parameters);
С юзером можно сразу роли через join достать, у тебя целых 3 запроса, чтобы просто получить пользователей и роли. Есть же соединительная таблица IdentityUserRoles, сделай в запросе два джоина, типа такого

```
SELECT 
    u.id AS user_id,
    u.username,
    r.role_name
FROM 
    users u
JOIN 
    user_roles ur ON u.id = ur.user_id
JOIN 
    roles r ON ur.role_id = r.id;
```

2024-10-24 14:58 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
Перед тем как отправлять запросы, лучше проверить, что у пользователя есть такие роли, а потом уже отправлять, чтобы не говорить миллион запросов

2024-10-24 14:58 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
А ещё лучше добавить к User соединительные ссылки с аккаунтами

2024-10-24 14:58 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
Тогда у user было бы например VolunteerAccoundId?

2024-10-24 17:19 UTC, McConderEz commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
Имеется в виду User из домена?

2024-10-24 17:20 UTC, McConderEz commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
Получится ли смаппить с одного запроса? Или ссылки для проверки наличия аккаунта добавить надо?

2024-10-24 18:05 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
Насчет одного запроса не знаю, но то, что надо доставать юзера с ролями вместеч это точно. Насчет аккаунтов надо думать, может и получится, если будут навигационные свойства, просто еще джоинов добавить

2024-10-24 18:07 UTC, McConderEz commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
в Dapper просто ограничение на 6 параметров для маппинга, а мне прокинуть еще нужно ,помимо 2 idшников аккаунтов, 2 строки(сертификаты и реквизиты волонтёра)

2024-10-24 18:08 UTC, McConderEz commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Queries/GetUserById/GetUserByIdHandler.cs
> +        var volunteerAccount = await GetVolunteerAccount(connection, parameters);
Вру, 7

2024-10-24 18:56 UTC, McConderEz commented
Пока что добился уменьшения до 3х запросов, с одним запросом не вышло.  VolunteerId и ParticipantId в User почему-то null. Либо явно его указывать юзеру после создания ParticipantAccount, но как будто бред.

2024-10-25 18:42 UTC, KirillSachkov commented
> Пока что добился уменьшения до 3х запросов, с одним запросом не вышло.  VolunteerId и ParticipantId в User почему-то null. Либо явно его указывать юзеру после создания ParticipantAccount, но как будто бред.

Не бред, можно явно аккаунту передавать навигационное свойство User и устанавливать его например. Так не пробовал? В любом случае попробуй еще разные варианты с навигационными свойствами, здесь их можно на каждом шагу указывать, если не получится, то апрув в любом случае. Я в будущем покажу как можно красиво с акккаунтами и юзером обойтись

2024-10-26 07:36 UTC, KirillSachkov approved these changes

2024-10-26 07:43 UTC, merged