Id b 25
McConderEz/AnimalAllies pull request #55
Opened 2024-10-31 22:00 UTC by McConderEz

2024-11-01 07:53 UTC, KirillSachkov requested changes

2024-11-01 07:53 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Commands/BanUser/BanUserCommand.cs
> +public record BanUserCommand(Guid UserId, Guid RelationId) : ICommand;
Ну не ban, а ограничить отпраку заявок на волонтерство, типа того

2024-11-01 07:53 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Application/AccountManagement/Commands/DeleteBanUser/DeleteBannedUserCommand.cs
> +public record DeleteBannedUserCommand(Guid UserId) : ICommand;
Что значит удалить забанненого пользователя, непонятно, нужно название приближенное к реальности

2024-11-01 07:53 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Domain/BannedUser.cs
> +    public Guid RelationId { get; private set; }
Что такое relationId?

2024-11-01 07:53 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Domain/BannedUser.cs
> +public class BannedUser: Entity<BannedUserId>
Данная модель не должна относится к модулю аккаунтов, так как здесь мы говорим просто про ограничение отправки заявок на волонтерство. Эту модель нужно перенести в модуль заявок на волонтерство и соответствуще её назвать

2024-11-01 07:53 UTC, KirillSachkov commented on backend/src/Discussion/Discussion.Application/Features/Commands/CreateDiscussion/CreateDiscussionHandler.cs
> +            return Errors.General.NotFound(command.SecondMember);
это можно проверить одним запросом

2024-11-01 08:02 UTC, McConderEz commented on backend/src/Accounts/AnimalAllies.Accounts.Domain/BannedUser.cs
> +    public Guid RelationId { get; private set; }
Я думал, что когда в задачке писалось про relationId, то мы вероятно будем использовать одну и ту же модель дискуссий в разных модулях. Как например между админом и пользователем при создании заявки на волонтёрство или при обсуждении деталей между волонтёром и пользователем. Тогда эту связь удалять?

2024-11-01 08:05 UTC, McConderEz commented on backend/src/Accounts/AnimalAllies.Accounts.Domain/BannedUser.cs
> +public class BannedUser: Entity<BannedUserId>
Если переносить туда,то под нее делать репозиторий?Она тоже будет агрегатом?

2024-11-01 08:19 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Domain/BannedUser.cs
> +    public Guid RelationId { get; private set; }
да, мы будем дискуссии использовать в разных местах, но причем здесь ограничение пользователя на отправку заявки? ограничение пользователя на отправку заявки относится только к заявкам.

2024-11-01 08:19 UTC, KirillSachkov commented on backend/src/Accounts/AnimalAllies.Accounts.Domain/BannedUser.cs
> +public class BannedUser: Entity<BannedUserId>
да

2024-11-01 08:21 UTC, McConderEz commented on backend/src/Accounts/AnimalAllies.Accounts.Domain/BannedUser.cs
> +    public Guid RelationId { get; private set; }
Тупанул, думал это дискуссия

2024-11-02 10:54 UTC, KirillSachkov requested changes

2024-11-02 10:54 UTC, KirillSachkov commented on backend/src/VolunteerRequests/VolunteerRequests.Application/Features/Commands/CreateVolunteerRequest/CreateVolunteerRequestHandler.cs
вот эту проверку можно сделать внутри доменной модели

2024-11-04 08:00 UTC, KirillSachkov approved these changes

2024-11-04 08:41 UTC, merged